# Generated by Django 4.1.2 on 2022-11-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
        ),
    ]
