# Generated by Django 4.1.2 on 2022-11-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_doings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doings',
            name='status',
            field=models.CharField(default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
