# Generated by Django 4.1.2 on 2022-11-17 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_doings_title_alter_doings_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doings',
            name='date',
        ),
        migrations.RemoveField(
            model_name='doings',
            name='status',
        ),
        migrations.RemoveField(
            model_name='doings',
            name='title',
        ),
        migrations.AddField(
            model_name='doings',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doings',
            name='summary',
            field=models.TextField(default='adasd', max_length=50, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doings',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновление'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.doings', verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.doings', verbose_name='Статус')),
            ],
        ),
    ]
