# Generated by Django 4.1.2 on 2022-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_doings_date_remove_doings_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_name',
            field=models.CharField(default='zczx', max_length=150, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='type_name',
            field=models.CharField(default='zczxczxcz', max_length=150, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doings',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='doings',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
    ]
