# Generated by Django 4.1.2 on 2022-11-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_status_status_name_type_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.doings', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.doings', verbose_name='Задача'),
        ),
    ]
