# Generated by Django 4.1.2 on 2022-11-18 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_status_status_alter_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
        migrations.AddField(
            model_name='doings',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.status', verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doings',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.type', verbose_name='Задача'),
            preserve_default=False,
        ),
    ]
