# Generated by Django 4.1.2 on 2022-11-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_status_status_remove_type_type_doings_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='statusname',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type_name',
            new_name='typename',
        ),
    ]
