# Generated by Django 4.1.2 on 2022-11-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_rename_status_name_status_statusname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doings',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='doings',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.type', verbose_name='Тип'),
        ),
    ]
