# Generated by Django 4.1.2 on 2022-11-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_doings_status_alter_doings_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doings',
            name='type',
        ),
        migrations.AddField(
            model_name='doings',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='type', to='webapp.type'),
        ),
    ]
